{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ap.secretName" . }}
  labels:
    {{- include "ap.labels" (dict "ctx" . "component" "config") | nindent 4 }}
type: Opaque
stringData:
  {{- include "ap.secretData" . | nindent 2 }}
{{- end }}
