"""A throwaway licence for the local and CI stack (``make dev-licence``). Dev only.

The production ``keys.py`` trusts only the vendor's key, so a stack built from
this repository runs as Community: three users and no Business features. The
end-to-end tests need Business features, so this writes, into ``--out``:

- ``keys.py``: a copy of :mod:`app.services.licensing.keys` that trusts a
  freshly generated key and nothing else;
- ``compose.licence.yml``: a compose override that mounts that file over the
  backend's and worker's ``keys.py`` and sets ``APP_LICENSE_KEY`` to a Business
  key signed with it.

Nothing here weakens a real install: the generated key is trusted only where
the generated ``keys.py`` is mounted, and its private half is discarded.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import uuid4

from app.services.licensing.issue import generate_keypair, issue
from app.services.licensing.license import BUSINESS, SCHEMA_VERSION

#: How long the dev licence lasts; regenerate with ``make dev-licence``.
VALID_DAYS = 90
SEATS = 25

#: The generated ``keys.py`` as compose sees it. Compose resolves an override's
#: relative paths against the project directory (the repository root), so this
#: holds wherever the generator ran, on the host or in a container.
MOUNT_SOURCE = "./.dev/keys.py"

#: Where the backend image keeps ``keys.py``: the source tree it runs from and
#: the installed package beside it.
_CONTAINER_PATHS = (
    "/app/app/services/licensing/keys.py",
    "/opt/venv/lib/python3.12/site-packages/app/services/licensing/keys.py",
)


def keys_module(kid: str, public_key: bytes) -> str:
    """Source of a ``keys.py`` that trusts only ``kid``."""
    return (
        '"""Dev-only vendor keys, generated by `make dev-licence`. Never ship this."""\n\n'
        "from __future__ import annotations\n\n"
        "from datetime import date\n\n"
        f"VENDOR_PUBLIC_KEYS: dict[str, bytes] = {{{kid!r}: bytes.fromhex({public_key.hex()!r})}}\n"
        "REVOKED_LICENSES: dict[str, date] = {}\n"
    )


def compose_override(licence_key: str, mount_source: str = MOUNT_SOURCE) -> str:
    """A compose override mounting the generated ``keys.py`` and setting the licence key."""
    mounts = "".join(f"      - {mount_source}:{target}:ro\n" for target in _CONTAINER_PATHS)
    service = (
        "    volumes:\n" + mounts + "    environment:\n"
        f"      APP_LICENSE_KEY: {json.dumps(licence_key)}\n"
    )
    return (
        "# Dev only, generated by `make dev-licence`: trusts a throwaway key.\n"
        f"services:\n  backend:\n{service}  worker:\n{service}"
    )


def write(out: Path, *, today: datetime | None = None) -> Path:
    """Write ``keys.py`` and ``compose.licence.yml`` into ``out``; return the override."""
    out.mkdir(parents=True, exist_ok=True)
    private_key, public_key = generate_keypair()
    kid = f"vdev{public_key.hex()[:8]}"
    issued = (today or datetime.now(UTC)).date()
    licence_key = issue(
        private_key,
        {
            "v": SCHEMA_VERSION,
            "kid": kid,
            "lic": str(uuid4()),
            "tier": BUSINESS,
            "licensee": "Local development",
            "seats": SEATS,
            "issued_at": issued.isoformat(),
            "expires_at": (issued + timedelta(days=VALID_DAYS)).isoformat(),
            "features": [],
        },
    )
    (out / "keys.py").write_text(keys_module(kid, public_key), encoding="utf-8")
    override = out / "compose.licence.yml"
    override.write_text(compose_override(licence_key), encoding="utf-8")
    return override


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="app.services.licensing.devlicence", description=__doc__)
    parser.add_argument("--out", type=Path, required=True, help="directory to write into")
    args = parser.parse_args(argv)
    print(f"wrote {write(args.out)}")


if __name__ == "__main__":
    main()
